parameters:
- name: branchName
  type: string
  default: 'main'
- name: projectName
  type: string
  default: 'RawflameManagement.API'
- name: projectDirectory
  default: $(Build.SourcesDirectory)\$(Build.Repository.Name)
  type: string
- name: pathToPublish
  type: string
  default: $(Build.ArtifactStagingDirectory)
- name: buildSolution
  type: string
  default: '**/*.sln'
- name: buildPlatform
  type: string
  default: AnyCPU
- name: buildConfiguration
  type: string
  default: Release
- name: agentImage
  type: string
  default: "windows-latest"
- name: dotnetVersion
  type: string
  default: '3.x'
- name: hasTest
  type: boolean
  default: true
- name: beforeBuildSteps # the name of the parameter is buildSteps
  type: stepList # data type is StepList
  default: [] # default value of buildSteps
- name: afterBuildSteps # the name of the parameter is buildSteps
  type: stepList # data type is StepList
  default: [] # default value of buildSteps
- name: RepoCheckoutName
  type: string

jobs:
- job: 'Build_${{parameters.RepoCheckoutName}}_Job' #Job name cannot have spaces
  displayName: 'App ${{parameters.RepoCheckoutName}} Build' #Name displayed when viewing in Azure DevOps
  variables:
  - name: nugetConfigPath
    value:  '${{parameters.projectDirectory}}/RawflameManagement.API/.nuget/NuGet.config'
  pool:
    vmImage: ${{ parameters.agentImage }} #See available agent images: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent
  steps:
  - checkout: "${{parameters.RepoCheckoutName}}"
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: ${{ parameters.dotnetVersion }}
      performMultiLevelLookup: true
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      projects: '**/RMU.WebAPI/*.csproj'
      feedsToUse: config
      nugetConfigPath: '${{parameters.projectDirectory}}/RawflameManagement.API/.nuget/NuGet.config'
      includeNuGetOrg: true

  - template: Templates/Tools/SonarQubeMsBuildStart.yml@TestAutomation
    parameters:
      projectName: ${{ parameters.projectName }}
      branchName: ${{ parameters.branchName }}
      workingDirectory: '${{ parameters.projectDirectory }}'

  - task: DotNetCoreCLI@2
    displayName: Publish App
    inputs:
      command: publish  #The publish command does a restore, build and creates a zip file so no need to add extra steps
      publishWebProjects: false
      zipAfterPublish: true
      projects:  '**/RMU.PI/*.csproj'
      arguments: '--configuration ${{ parameters.buildConfiguration }} --output ${{ parameters.pathToPublish }}'
 
  - template: Templates/Tools/SonarQubeMsBuildEnd.yml@TestAutomation 
    parameters:
      branchName: ${{ parameters.branchName }}
        
  - task: DotNetCoreCLI@2
    enabled: ${{ parameters.hasTest}}
    displayName: Test
    inputs:
      command: test #Don't forget to test!
      projects: '**/*.Test.csproj'
      arguments: '--configuration Release'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact'
    inputs:
      targetPath: '${{ parameters.pathToPublish }}'
      artifactName: 'api${{ parameters.projectName }}'

  - ${{ if and(ne( variables['Build.Reason'], 'PullRequest' ), in(variables['Build.SourceBranchName'], 'dev','main','master') ) }}:
    - template: Templates/Tools/whitesourceScanSteps.yml@TestAutomation
      parameters:
        wsConfigFile: 'whiteSource-file.config'
        artifactsPath: ${{ parameters.pathToPublish }}
        pullTemplateRepo: true
        productName: 'RMU-$(Build.SourceBranchName)'
        projectName: ${{ parameters.projectName }}
        userKey: $(userKey-RMU)
