parameters:
- name: RunSkynet
  type: boolean
  default: false 
  
- name: RunRMU
  type: boolean
  default: false 
  

stages:
- stage: 'Build_Stage' #Stage name cannot have spaces
  displayName: 'Build' #Name displayed when viewing in Azure DevOps
  jobs:

################# Skynet API ##################
  - ${{ if eq(parameters.RunSkynet, true)}}:
    - template: Pipeline/Templates/build-template-jobs.yml@SkynetApi
      parameters:
        projectName: 'Skynet.API'
        projectDirectory: $(Build.SourcesDirectory)/$(SkynetApi.name)
        RepoCheckoutName: 'SkynetApi' 
        hasTest: ${{parameters.EnableUnitTest}} 
        
##################### Rawflame Management #######################
  - ${{ if eq(parameters.RunRMU, true)}}:
    - template: Pipeline/Templates/build-template-micro-jobs.yml@RMU
      parameters:
        projectName: 'RawflameManagement.API'
        projectDirectory: $(Build.SourcesDirectory)/$(RMU.name)
        RepoCheckoutName: 'RMU' 
