parameters:
- name: 'Stage'
  type: string

- name: 'Dependency'
  type: string   

- name: RunSkynet
  type: boolean
  default: false 

- name: RunRMU
  type: boolean
  default: false 

- name: 'AzureSubscription'
  type: string

stages:
- stage: '${{parameters.Stage}}'
  displayName: 'Deploy to ${{parameters.Stage}}'
  dependsOn: ${{parameters.Dependency}}
  variables:
  - template: "../Variables/var_${{parameters.Stage}}.yml"
  jobs:

################################################################################################
################# Enable dependency if needed based on app config requirement ##################
################################################################################################

############## Skynet API ##################
  - ${{ if eq(parameters.RunSkynet, true)}}:
    - template: Pipeline/Templates/deploy-template-cd.yml@SkynetApi
      parameters:
        Stage: ${{parameters.Stage}}
        ProjectName: 'Skynet.API'
        AzureSubscription: ${{parameters.AzureSubscription}}
        projectDirectory:  $(Build.SourcesDirectory)/$(SkynetApi.name)
        RepoCheckoutName: 'SkynetApi'
        AppServiceName: '$(SkynetAppServiceName)-api'
        ResourceGroup: $(SkynetAppServiceName)
        DatabaseServerName: $(SkynetAppServiceName)-sql
        DatabaseName: $(SkynetAppServiceName)-db
        AppServicePlanName: $(SkynetAppServiceName)-sp
        webAppSlot: $(webAppSlot)
        AppServicePlanSku: $(AppServicePlanSku)
        KeyVaultName: $(KeyVaultName)
        Location: $(Location)
        DatabaseEdition: $(DatabaseEdition)
        DatabaseSku: $(DatabaseSku)
        AzureSubscriptionId: $(AzureSubscriptionId)
        Tags: $(Tags)
        appInsightName: '$(RegionCode)-SaaS-Snet-001-${{parameters.Stage}}-WEB'

################# Rawflame Management ##################
  - ${{ if eq(parameters.RunRMU, true)}}:
    - template: Pipeline/Templates/deploy-template-jobs.yml@RMU
      parameters:
        Stage: ${{parameters.Stage}}
        ProjectName: 'RawflameManagement.API'
        AzureSubscription: ${{parameters.AzureSubscription}}
        projectDirectory:  $(Build.SourcesDirectory)/$(RMU.name)
        RepoCheckoutName: 'RMU'
        ServiceLogAppServiceName: '$(RMUAppServiceName)-api'
        AppServiceName: $(RMUAppServiceName)-api
        AppServicePlanName: $(RMUAppServiceName)-sp
        appInsightName: '$(RegionCode)-SaaS-RMU-001-${{parameters.Stage}}-WEB'
        ResourceGroup: $(RMUAppServiceName)
        DatabaseServerName: $(RMUAppServiceName)-sql
        DatabaseName: $(RMUAppServiceName)-db
        webAppSlot: $(webAppSlot)
        AppServicePlanSku: $(AppServicePlanSku)
        Location: $(Location)
        DatabaseEdition: $(DatabaseEdition)
        DatabaseSku: $(DatabaseSku)
        AzureSubscriptionId: $(AzureSubscriptionId)
        DbSecretUser: $(CMUDbSecretUser)
        DbSecretPassword: $(CMUDbSecretPassword)
        Tags: $(Tags)
        IdsClientSecretCMUPortal: $(IdsClientSecretCMUPortal)
        KeyVaultName: $(KeyVaultName)
        CMUConStringSecretName: $(CMUConStringSecretName)
        WorkspacesResourceGroupName: $(WorkspacesResourceGroupName)
        WorkspacesName: $(WorkspacesName)

